In [2]:
import pandas as pd

data_set = pd.read_csv("/Users/proudchris/Desktop/ML_modeling/data/week1_macro_practice.csv")

data_set.head()

,date,industrial_production_index,pmi,policy_rate,exports_usd_billion,imports_usd_billion,cpi_yoy,unemployment_rate
0,2021-01-31,96.8,49.8,0.5,44.7,42.1,0.6,4.1
1,2021-02-28,97.4,50.2,0.5,45.3,42.7,0.8,4.0
2,2021-03-31,98.9,51.1,0.5,46.9,44.2,1.1,3.9
3,2021-04-30,99.6,51.8,0.5,48.2,45.1,1.4,3.8
4,2021-05-31,100.3,52.4,0.5,49.0,46.3,1.7,3.7

In [3]:
data_set.date = pd.to_datetime(data_set.date)

In [4]:
data_set.dtypes

date                           datetime64[us]
industrial_production_index           float64
pmi                                   float64
policy_rate                           float64
exports_usd_billion                   float64
imports_usd_billion                   float64
cpi_yoy                               float64
unemployment_rate                     float64
dtype: object

In [22]:
data_set = data_set.sort_values('date')

In [32]:
data_set.describe()

,date,industrial_production_index,pmi,policy_rate,exports_usd_billion,imports_usd_billion,cpi_yoy,unemployment_rate
count,49,48.000000,48.000000,49.000000,49.000000,48.000000,49.000000,49.000000
mean,2023-01-10 14:12:14.693877,105.387500,50.662500,2.408163,56.540816,55.202083,3.185714,3.214286
min,2021-01-31 00:00:00,96.800000,46.900000,0.500000,44.700000,42.100000,0.600000,2.700000
25%,2022-01-31 00:00:00,103.125000,49.875000,1.250000,53.100000,53.775000,2.300000,2.900000
50%,2022-12-31 00:00:00,105.150000,50.850000,3.250000,56.400000,56.000000,2.800000,3.200000
75%,2023-12-31 00:00:00,108.100000,52.025000,3.500000,60.600000,59.100000,4.200000,3.400000
max,2024-12-31 00:00:00,112.900000,53.200000,3.500000,66.800000,62.600000,5.900000,4.100000
std,NaN,3.855122,1.735686,1.227606,5.445331,5.178823,1.340864,0.340955

In [23]:
data_set.pmi.describe()

count    48.000000
mean     50.662500
std       1.735686
min      46.900000
25%      49.875000
50%      50.850000
75%      52.025000
max      53.200000
Name: pmi, dtype: float64

In [24]:
data_set.mean()

date                           2023-01-10 14:12:14.693877
industrial_production_index                      105.3875
pmi                                               50.6625
policy_rate                                      2.408163
exports_usd_billion                             56.540816
imports_usd_billion                             55.202083
cpi_yoy                                          3.185714
unemployment_rate                                3.214286
dtype: object

In [25]:
data_set.min()

date                           2021-01-31 00:00:00
industrial_production_index                   96.8
pmi                                           46.9
policy_rate                                    0.5
exports_usd_billion                           44.7
imports_usd_billion                           42.1
cpi_yoy                                        0.6
unemployment_rate                              2.7
dtype: object

In [26]:
data_set.max()

date                           2024-12-31 00:00:00
industrial_production_index                  112.9
pmi                                           53.2
policy_rate                                    3.5
exports_usd_billion                           66.8
imports_usd_billion                           62.6
cpi_yoy                                        5.9
unemployment_rate                              4.1
dtype: object

In [27]:
data_set.date.max()

Timestamp('2024-12-31 00:00:00')

In [28]:
data_set.cpi_yoy.min()

np.float64(0.6)

In [29]:
data_set.exports_usd_billion.mean()

np.float64(56.54081632653061)

In [30]:
data_set.industrial_production_index.max()

np.float64(112.9)