In [1]:
import pandas as pd

ds = pd.read_csv('../../../data/week4_korea_cli.csv')

In [4]:
ds.observation_date = pd.to_datetime(ds.observation_date)
ds = ds.sort_values('observation_date')

In [5]:
ds.isna().sum()

observation_date    0
KORLOLITOAASTSAM    0
dtype: int64

In [8]:
ds.describe()

                 observation_date  KORLOLITOAASTSAM
count                         438        438.000000
mean   2008-03-16 18:27:56.712328         99.993123
min           1990-01-01 00:00:00         94.805464
25%           1999-02-08 00:00:00         98.979399
50%           2008-03-16 12:00:00         99.983887
75%           2017-04-23 12:00:00        100.942811
max           2026-06-01 00:00:00        105.562636
std                           NaN          1.714661

In [9]:
ds.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
433    False
434    False
435    False
436    False
437    False
Length: 438, dtype: bool

In [10]:
ds.shape

(438, 2)

In [11]:
ds.columns

Index(['observation_date', 'KORLOLITOAASTSAM'], dtype='str')

In [12]:
ds.dtypes

observation_date    datetime64[us]
KORLOLITOAASTSAM           float64
dtype: object

In [13]:
ds.observation_date.is_monotonic_increasing

True

In [14]:
ds.loc[ds.isna().any(axis=1)]

Empty DataFrame
Columns: [observation_date, KORLOLITOAASTSAM]
Index: []

In [15]:
ds

    observation_date  KORLOLITOAASTSAM
0         1990-01-01        100.461861
1         1990-02-01        100.462284
2         1990-03-01        100.536374
3         1990-04-01        100.613811
4         1990-05-01        100.646672
..               ...               ...
433       2026-02-01        101.597894
434       2026-03-01        102.001885
435       2026-04-01        102.363604
436       2026-05-01        102.657914
437       2026-06-01        102.869808

[438 rows x 2 columns]

In [ ]:
# Index, Seasonally Adjusted (사이트에서 찾은 정보)

dtype('float64')