In [157]:
import pandas as pd
import numpy as np

ds = pd.read_csv('../../../data/week4_korea_cli.csv')
ds

    observation_date  KORLOLITOAASTSAM
0         1990-01-01        100.461861
1         1990-02-01        100.462284
2         1990-03-01        100.536374
3         1990-04-01        100.613811
4         1990-05-01        100.646672
..               ...               ...
433       2026-02-01        101.597894
434       2026-03-01        102.001885
435       2026-04-01        102.363604
436       2026-05-01        102.657914
437       2026-06-01        102.869808

[438 rows x 2 columns]

In [158]:
ds.observation_date = pd.to_datetime(ds.observation_date)
ds = ds.sort_values('observation_date')

In [159]:
ds['target_next_month'] = ds['KORLOLITOAASTSAM'].shift(-1).copy()
ds['baseline'] = ds['KORLOLITOAASTSAM'].copy()
ds['cli_lag1'] = ds['KORLOLITOAASTSAM'].shift(1).copy()
ds['cli_rolling3'] = ds['KORLOLITOAASTSAM'].rolling(window=3).mean()
ds['cli_diff1'] = ds['KORLOLITOAASTSAM'].diff(1)

In [160]:
month = ds['observation_date'].dt.month

ds['month_sin'] = np.sin(2 * np.pi * month / 12)
ds['month_cos'] = np.cos(2 * np.pi * month / 12)

In [161]:
set_A = ['cli_lag1', 'cli_rolling3']
set_B = ['cli_lag1', 'cli_rolling3', 'cli_diff1']
set_C = ['cli_lag1', 'cli_rolling3', 'cli_diff1', 'month_sin', 'month_cos']

In [162]:
ds

,observation_date,KORLOLITOAASTSAM,target_next_month,baseline,cli_lag1,cli_rolling3,cli_diff1,month_sin,month_cos
0,1990-01-01,100.461861,100.462284,100.461861,NaN,NaN,NaN,5.000000e-01,8.660254e-01
1,1990-02-01,100.462284,100.536374,100.462284,100.461861,NaN,0.000423,8.660254e-01,5.000000e-01
2,1990-03-01,100.536374,100.613811,100.536374,100.462284,100.486840,0.074089,1.000000e+00,6.123234e-17
3,1990-04-01,100.613811,100.646672,100.613811,100.536374,100.537490,0.077438,8.660254e-01,-5.000000e-01
4,1990-05-01,100.646672,100.610137,100.646672,100.613811,100.598952,0.032861,5.000000e-01,-8.660254e-01
...,...,...,...,...,...,...,...,...,...
433,2026-02-01,101.597894,102.001885,101.597894,101.190196,101.200525,0.407698,8.660254e-01,5.000000e-01
434,2026-03-01,102.001885,102.363604,102.001885,101.597894,101.596658,0.403991,1.000000e+00,6.123234e-17
435,2026-04-01,102.363604,102.657914,102.363604,102.001885,101.987795,0.361719,8.660254e-01,-5.000000e-01
436,2026-05-01,102.657914,102.869808,102.657914,102.363604,102.341134,0.294310,5.000000e-01,-8.660254e-01
437,2026-06-01,102.869808,NaN,102.869808,102.657914,102.630442,0.211894,1.224647e-16,-1.000000e+00

In [163]:
ds = ds.dropna(subset=['cli_lag1', 'cli_rolling3', 'cli_diff1', 'KORLOLITOAASTSAM', 'target_next_month'])
ds

,observation_date,KORLOLITOAASTSAM,target_next_month,baseline,cli_lag1,cli_rolling3,cli_diff1,month_sin,month_cos
2,1990-03-01,100.536374,100.613811,100.536374,100.462284,100.486840,0.074089,1.000000e+00,6.123234e-17
3,1990-04-01,100.613811,100.646672,100.613811,100.536374,100.537490,0.077438,8.660254e-01,-5.000000e-01
4,1990-05-01,100.646672,100.610137,100.646672,100.613811,100.598952,0.032861,5.000000e-01,-8.660254e-01
5,1990-06-01,100.610137,100.477904,100.610137,100.646672,100.623540,-0.036535,1.224647e-16,-1.000000e+00
6,1990-07-01,100.477904,100.254061,100.477904,100.610137,100.578238,-0.132233,-5.000000e-01,-8.660254e-01
...,...,...,...,...,...,...,...,...,...
432,2026-01-01,101.190196,101.597894,101.190196,100.813483,100.830936,0.376713,5.000000e-01,8.660254e-01
433,2026-02-01,101.597894,102.001885,101.597894,101.190196,101.200525,0.407698,8.660254e-01,5.000000e-01
434,2026-03-01,102.001885,102.363604,102.001885,101.597894,101.596658,0.403991,1.000000e+00,6.123234e-17
435,2026-04-01,102.363604,102.657914,102.363604,102.001885,101.987795,0.361719,8.660254e-01,-5.000000e-01
436,2026-05-01,102.657914,102.869808,102.657914,102.363604,102.341134,0.294310,5.000000e-01,-8.660254e-01

In [164]:
ds.columns

Index(['observation_date', 'KORLOLITOAASTSAM', 'target_next_month', 'baseline',
       'cli_lag1', 'cli_rolling3', 'cli_diff1', 'month_sin', 'month_cos'],
      dtype='str')

In [165]:
ds.observation_date.min(), ds.observation_date.max()

(Timestamp('1990-03-01 00:00:00'), Timestamp('2026-05-01 00:00:00'))

In [173]:
train = ds[(ds.observation_date >= pd.to_datetime('2000-01-01')) & (ds.observation_date <= pd.to_datetime('2014-12-01'))].copy()
validation = ds[(ds.observation_date >= pd.to_datetime('2015-01-01')) & (ds.observation_date <= pd.to_datetime('2019-12-01'))].copy()

len(train), len(validation)

(180, 60)

In [167]:
from sklearn.linear_model import LinearRegression

model_A = LinearRegression()
model_B = LinearRegression()
model_C = LinearRegression()

In [168]:
X_train_A = train[set_A].copy()
X_train_B = train[set_B].copy()
X_train_C = train[set_C].copy()

y_train = train['target_next_month']

In [169]:
model_A.fit(X_train_A, y_train)
model_B.fit(X_train_B, y_train)
model_C.fit(X_train_C, y_train)

LinearRegression()

In [ ]:
validation['model_predict_A'] = model_A.predict(validation[set_A])
validation['model_predict_B'] = model_B.predict(validation[set_B])
validation['model_predict_C'] = model_C.predict(validation[set_C])

In [ ]:
y_answer = validation.target_next_month.copy()

result = pd.DataFrame(index=['base', 'A', 'B', 'C'])

result.loc['base', 'model'] = 'baseline'
result.loc['base', 'feature_count'] = 1
result.loc['base', 'validation_rows'] = len(validation)
result.loc['base', 'MAE'] = (y_answer - validation.baseline).abs().mean()
result.loc['base', 'RMSE'] = np.sqrt(((y_answer - validation.baseline)**2).mean())

result.loc['A', 'model'] = 'model A'
result.loc['A', 'feature_count'] = len(set_A)
result.loc['A', 'validation_rows'] = len(validation)
result.loc['A', 'MAE'] = (y_answer - validation.model_predict_A).abs().mean()
result.loc['A', 'RMSE'] = np.sqrt(((y_answer - validation.model_predict_A)**2).mean())


result.loc['B', 'model'] = 'model B'
result.loc['B', 'feature_count'] = len(set_B)
result.loc['B', 'validation_rows'] = len(validation)
result.loc['B', 'MAE'] = (y_answer - validation.model_predict_B).abs().mean()
result.loc['B', 'RMSE'] = np.sqrt(((y_answer - validation.model_predict_B)**2).mean())


result.loc['C', 'model'] = 'model C'
result.loc['C', 'feature_count'] = len(set_C)
result.loc['C', 'validation_rows'] = len(validation)
result.loc['C', 'MAE'] = (y_answer - validation.model_predict_C).abs().mean()
result.loc['C', 'RMSE'] = np.sqrt(((y_answer - validation.model_predict_C)**2).mean())

In [172]:
result

         model  feature_count  validation_rows       MAE      RMSE
base  baseline            1.0             60.0  0.079752  0.093522
A      model A            2.0             60.0  0.177627  0.211966
B      model B            3.0             60.0  0.010768  0.013730
C      model C            5.0             60.0  0.012138  0.015409